# Generated by Django 5.2.7 on 2025-11-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_experience_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, default='images/20200501_noimage.jpg', null=True, upload_to='experience_images'),
        ),
    ]
