# Generated by Django 5.2.7 on 2025-11-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_experience_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='images/20200501_noimage.jpg', null=True, upload_to='images'),
        ),
    ]
